# Generated by Django 3.2.4 on 2021-12-05 11:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('day', models.CharField(max_length=20)),
                ('batch', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='LocationTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('Computer Lab 1-a', 'Computer Lab 1-a'), ('Computer Lab 1-b', 'Computer Lab 1-b'), ('Computer Lab 2-a', 'Computer Lab 2-a'), ('Computer Lab 2-b', 'Computer Lab 2-b'), ('Computer Lab 3-a', 'Computer Lab 3-a'), ('Computer Lab 3-b', 'Computer Lab 3-b'), ('Computer Lab 4-a', 'Computer Lab 4-a'), ('Computer Lab 4-b', 'Computer Lab 4-b'), ('Electronics lab', 'Electronics lab'), ('Sports Room', 'Sports Room'), ('Library', 'Library')], max_length=40)),
                ('tag_id_id', models.CharField(max_length=15)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('tag_id', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('div', models.CharField(max_length=3)),
                ('roll', models.IntegerField()),
                ('name', models.CharField(max_length=80)),
                ('course', models.CharField(choices=[('BSc.Computer Science', 'BSc.Computer Science'), ('BSc.Computer Application', 'BSc.Computer Application'), ('BSc.IT Cyber Crime', 'BSc.IT Cyber Crime'), ('BCom', 'BCom'), ('BBA', 'BBA'), ('MBA', 'MBA'), ('MSc.Computer Science', 'MSc.Computer Science'), ('MSc.Computer Application', 'MSc.Computer Application')], max_length=30)),
                ('year', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherRegister',
            fields=[
                ('t_name', models.CharField(max_length=80)),
                ('tag_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('course', models.CharField(choices=[('BSc.Computer Science', 'BSc.Computer Science'), ('BSc.Computer Application', 'BSc.Computer Application'), ('BSc.IT Cyber Crime', 'BSc.IT Cyber Crime'), ('BCom', 'BCom'), ('BBA', 'BBA'), ('MBA', 'MBA'), ('MSc.Computer Science', 'MSc.Computer Science'), ('MSc.Computer Application', 'MSc.Computer Application')], max_length=30)),
                ('practical_subject', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('BSc.Computer Science', 'BSc.Computer Science'), ('BSc.Computer Application', 'BSc.Computer Application'), ('BSc.IT Cyber Crime', 'BSc.IT Cyber Crime'), ('BCom', 'BCom'), ('BBA', 'BBA'), ('MBA', 'MBA'), ('MSc.Computer Science', 'MSc.Computer Science'), ('MSc.Computer Application', 'MSc.Computer Application')], max_length=30)),
                ('year', models.CharField(choices=[('FY', 'FY'), ('SY', 'SY'), ('TY', 'TY')], max_length=12)),
                ('area', models.CharField(choices=[('Computer Lab 1-a', 'Computer Lab 1-a'), ('Computer Lab 1-b', 'Computer Lab 1-b'), ('Computer Lab 2-a', 'Computer Lab 2-a'), ('Computer Lab 2-b', 'Computer Lab 2-b'), ('Computer Lab 3-a', 'Computer Lab 3-a'), ('Computer Lab 3-b', 'Computer Lab 3-b'), ('Computer Lab 4-a', 'Computer Lab 4-a'), ('Computer Lab 4-b', 'Computer Lab 4-b'), ('Electronics lab', 'Electronics lab'), ('Sports Room', 'Sports Room'), ('Library', 'Library')], max_length=40)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('Monday', models.CharField(max_length=30)),
                ('Tuesday', models.CharField(max_length=30)),
                ('Wednesday', models.CharField(max_length=30)),
                ('Thursday', models.CharField(max_length=30)),
                ('Friday', models.CharField(max_length=30)),
                ('Saturday', models.CharField(max_length=30)),
                ('Sunday', models.CharField(max_length=30)),
                ('student', models.ManyToManyField(editable=False, through='page.AttendanceRecord', to='page.Register')),
            ],
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.timetable'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.register'),
        ),
    ]
