# Generated by Django 3.2.4 on 2021-06-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_alter_timetable_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationtrack',
            name='tag_id_id',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='teacherregister',
            name='tag_id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
