# Generated by Django 3.2.4 on 2021-06-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20210609_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('BSc.Computer Science', 'BSc.Computer Science'), ('BSc.Computer Application', 'BSc.Computer Application'), ('BSc.IT Cyber Crime', 'BSc.IT Cyber Crime'), ('BCom', 'BCom'), ('BBA', 'BBA'), ('MBA', 'MBA'), ('MSc.Computer Science', 'MSc.Computer Science'), ('MSc.Computer Application', 'MSc.Computer Application')], max_length=30)),
                ('academic_year', models.CharField(max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('attendance_date', models.DateField()),
                ('attendance_day', models.CharField(max_length=20)),
                ('attendance_count', models.IntegerField()),
                ('std_name', models.CharField(max_length=80)),
                ('std_roll', models.IntegerField()),
                ('std_div', models.CharField(max_length=5)),
                ('attendance_batch', models.CharField(max_length=25)),
                ('attendance_location', models.CharField(max_length=40)),
            ],
        ),
    ]
