# Generated by Django 3.2.4 on 2021-06-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_attendancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='tag_id',
            field=models.CharField(default='1', max_length=15),
            preserve_default=False,
        ),
    ]
